//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log_Mascotas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-RV58URL;Initial Catalog=App_Mi_Mascota;Integrated Security=Tr" +
            "ue;TrustServerCertificate=True")]
        public string App_Mi_MascotaConnectionString {
            get {
                return ((string)(this["App_Mi_MascotaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CJ3PQUD;Initial Catalog=App_Mi_Mascota;Integrated Security=Tr" +
            "ue;Encrypt=True;TrustServerCertificate=True")]
        public string App_Mi_MascotaConnectionString1 {
            get {
                return ((string)(this["App_Mi_MascotaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-RV58URL;Initial Catalog=App_Mi_Mascota;Integrated Security=Tr" +
            "ue;Encrypt=True;TrustServerCertificate=True")]
        public string App_Mi_MascotaConnectionString2 {
            get {
                return ((string)(this["App_Mi_MascotaConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2490RMR;Initial Catalog=App_Mi_Mascota;Integrated Security=Tr" +
            "ue;Encrypt=True;TrustServerCertificate=True")]
        public string App_Mi_MascotaConnectionString3 {
            get {
                return ((string)(this["App_Mi_MascotaConnectionString3"]));
            }
        }
    }
}
