#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log_Mascotas.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="App_Mi_Mascota")]
	public partial class ConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConexionDataContext() : 
				base(global::Log_Mascotas.Properties.Settings.Default.App_Mi_MascotaConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTIVAR_USUARIO")]
		public int SP_ACTIVAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(MAX)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMEROVERIFICACION", DbType="NVarChar(MAX)")] string nUMEROVERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FILASACTUALIZADAS", DbType="Int")] ref System.Nullable<int> fILASACTUALIZADAS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO, nUMEROVERIFICACION, iDRETURN, eRRORID, eRRORDESCRIPCION, fILASACTUALIZADAS);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			fILASACTUALIZADAS = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_USUARIO")]
		public int SP_ACTUALIZAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(100)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(100)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(100)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONFIRMACION_DE_CORREO_ELECTRONICO", DbType="NVarChar(100)")] string cONFIRMACION_DE_CORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(100)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONFIRMACION_PASSWORD", DbType="NVarChar(100)")] string cONFIRMACION_PASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, nOMBRE, aPELLIDOS, cORREO_ELECTRONICO, cONFIRMACION_DE_CORREO_ELECTRONICO, pASSWORD, cONFIRMACION_PASSWORD, idReturn, idError, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(7)));
			idError = ((System.Nullable<int>)(result.GetParameterValue(8)));
			errorDescripcion = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AGREGAR_BAHEIRO")]
		public int SP_AGREGAR_BAHEIRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_DE_BAHEIRO", DbType="NVarChar(255)")] string tIPO_DE_BAHEIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tIPO_DE_BAHEIRO, dESCRIPCION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BAHEIROS_MASCOTAS")]
		public int SP_BAHEIROS_MASCOTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MASCOTA", DbType="Int")] System.Nullable<int> iD_MASCOTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_BAHEIRO", DbType="Int")] System.Nullable<int> iD_BAHEIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_Y_HORA_BAHEIRO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_Y_HORA_BAHEIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_Y_HORA_PROXIMO_BAHEIRO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_Y_HORA_PROXIMO_BAHEIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOTAS", DbType="NVarChar(255)")] string nOTAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MASCOTA, iD_BAHEIRO, fECHA_Y_HORA_BAHEIRO, fECHA_Y_HORA_PROXIMO_BAHEIRO, nOTAS, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CITAS__CLINICA_VETERINARIA_MASCOTAS")]
		public ISingleResult<SP_CITAS__CLINICA_VETERINARIA_MASCOTASResult> SP_CITAS__CLINICA_VETERINARIA_MASCOTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MASCOTA", DbType="Int")] System.Nullable<int> iD_MASCOTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CLINICA_VETERINARIA", DbType="Int")] System.Nullable<int> iD_CLINICA_VETERINARIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_DOCTOR", DbType="Int")] System.Nullable<int> iD_DOCTOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_Y_HORA", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_Y_HORA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOTAS", DbType="NVarChar(255)")] string nOTAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESULTADO", DbType="Int")] ref System.Nullable<int> rESULTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ERROR", DbType="Int")] ref System.Nullable<int> iD_ERROR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPCION", DbType="VarChar(200)")] ref string eRROR_DESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MASCOTA, iD_CLINICA_VETERINARIA, iD_DOCTOR, fECHA_Y_HORA, dESCRIPCION, nOTAS, rESULTADO, iD_ERROR, eRROR_DESCRIPCION);
			rESULTADO = ((System.Nullable<int>)(result.GetParameterValue(6)));
			iD_ERROR = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRROR_DESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((ISingleResult<SP_CITAS__CLINICA_VETERINARIA_MASCOTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CLINICA_VETERINARIA")]
		public int SP_CLINICA_VETERINARIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_CLINICA_VETERINARIA", DbType="NVarChar(255)")] string nOMBRE_CLINICA_VETERINARIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_DOCTOR", DbType="Int")] System.Nullable<int> iD_DOCTOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="NVarChar(255)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="NVarChar(20)")] string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ERROR", DbType="Int")] ref System.Nullable<int> iD_ERROR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPCION", DbType="VarChar(200)")] ref string eRROR_DESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_CLINICA_VETERINARIA, iD_DOCTOR, dIRECCION, tELEFONO, iDRETURN, iD_ERROR, eRROR_DESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			iD_ERROR = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRROR_DESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_USUARIO")]
		public int SP_ELIMINAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correoElectronico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, correoElectronico, idReturn, idError, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(2)));
			idError = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_DOCTOR")]
		public int SP_INGRESAR_DOCTOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="VarChar(50)")] string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="VarChar(50)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, tELEFONO, cORREO_ELECTRONICO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_FOTOS")]
		public int SP_INGRESAR_FOTOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Foto", DbType="VarBinary(MAX)")] System.Data.Linq.Binary foto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Mascota", DbType="Int")] System.Nullable<int> id_Mascota, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(255)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), foto, id_Mascota, descripcion, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_MASCOTA")]
		public int SP_INGRESAR_MASCOTA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESPECIE", DbType="NVarChar(50)")] string eSPECIE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RAZA", DbType="NVarChar(50)")] string rAZA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_NACIMIENTO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_NACIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MASCOTA", DbType="Int")] ref System.Nullable<int> iD_MASCOTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO, nOMBRE, eSPECIE, rAZA, fECHA_NACIMIENTO, iD_MASCOTA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iD_MASCOTA = ((System.Nullable<int>)(result.GetParameterValue(5)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_MASCOTA_MEDICAMENTO")]
		public int SP_INGRESAR_MASCOTA_MEDICAMENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MASCOTA", DbType="Int")] System.Nullable<int> iD_MASCOTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MEDICAMENTO", DbType="Int")] System.Nullable<int> iD_MEDICAMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MODO_DE_ADMINISTRACION", DbType="VarChar(20)")] string mODO_DE_ADMINISTRACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_INICIO", DbType="Date")] System.Nullable<System.DateTime> fECHA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_FIN", DbType="Date")] System.Nullable<System.DateTime> fECHA_FIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA_DE_INGESTA", DbType="Time")] System.Nullable<System.TimeSpan> hORA_DE_INGESTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOTAS", DbType="NVarChar(255)")] string nOTAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MASCOTA, iD_MEDICAMENTO, mODO_DE_ADMINISTRACION, fECHA_INICIO, fECHA_FIN, hORA_DE_INGESTA, nOTAS, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_MASCOTAS_VACUNAS")]
		public int SP_INGRESAR_MASCOTAS_VACUNAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MASCOTA", DbType="Int")] System.Nullable<int> iD_MASCOTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_VACUNA", DbType="Int")] System.Nullable<int> iD_VACUNA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOSIS", DbType="Int")] System.Nullable<int> dOSIS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_Y_HORA_APLICACION", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_Y_HORA_APLICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_Y_HORA_PROXIMA_APLICACION", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_Y_HORA_PROXIMA_APLICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COMENTARIOS", DbType="NVarChar(MAX)")] string cOMENTARIOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDERROR", DbType="Int")] ref System.Nullable<int> iDERROR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(200)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MASCOTA, iD_VACUNA, dOSIS, fECHA_Y_HORA_APLICACION, fECHA_Y_HORA_PROXIMA_APLICACION, cOMENTARIOS, iDRETURN, iDERROR, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			iDERROR = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_MEDICAMENTO")]
		public int SP_INGRESAR_MEDICAMENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CATEGORIA", DbType="VarChar(50)")] string cATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_VENCIMIENTO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_VENCIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, cATEGORIA, dESCRIPCION, fECHA_VENCIMIENTO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_USUARIO")]
		public int SP_INGRESAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(50)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(50)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONFIRMACION_DE_CORREO_ELECTRONICO", DbType="NVarChar(255)")] string cONFIRMACION_DE_CORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="VarChar(255)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONFIRMACION_PASSWORD", DbType="VarChar(255)")] string cONFIRMACION_PASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_VERIFICACION", DbType="NVarChar(MAX)")] string nUMERO_VERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] ref System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorId", DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorDescripcion", DbType="NVarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDOS, cORREO_ELECTRONICO, cONFIRMACION_DE_CORREO_ELECTRONICO, pASSWORD, cONFIRMACION_PASSWORD, nUMERO_VERIFICACION, iD_USUARIO, errorId, errorDescripcion);
			iD_USUARIO = ((System.Nullable<int>)(result.GetParameterValue(7)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(8)));
			errorDescripcion = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_VACUNA")]
		public int SP_INGRESAR_VACUNA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_VENCIMIENTO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_VENCIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, dESCRIPCION, fECHA_VENCIMIENTO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_CLINICA_DOCTOR")]
		public int SP_INSERTAR_CLINICA_DOCTOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CLINICA_VETERINARIA", DbType="Int")] System.Nullable<int> iD_CLINICA_VETERINARIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_DOCTOR", DbType="Int")] System.Nullable<int> iD_DOCTOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CLINICA_VETERINARIA, iD_DOCTOR);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_RECORDATORIO")]
		public int SP_INSERTAR_RECORDATORIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MASCOTA", DbType="Int")] System.Nullable<int> iD_MASCOTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA", DbType="Date")] System.Nullable<System.DateTime> fECHA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA", DbType="Time")] System.Nullable<System.TimeSpan> hORA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(50)")] string tIPO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_VACUNA", DbType="Int")] System.Nullable<int> iD_VACUNA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MEDICAMENTO", DbType="Int")] System.Nullable<int> iD_MEDICAMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CITA", DbType="Int")] System.Nullable<int> iD_CITA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_BAHEIRO", DbType="Int")] System.Nullable<int> iD_BAHEIRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDERROR", DbType="Int")] ref System.Nullable<int> iDERROR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="VarChar(200)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MASCOTA, fECHA, hORA, dESCRIPCION, tIPO, nOMBRE, iD_VACUNA, iD_MEDICAMENTO, iD_CITA, iD_BAHEIRO, iDRETURN, iDERROR, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(10)));
			iDERROR = ((System.Nullable<int>)(result.GetParameterValue(11)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(12)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN")]
		public int SP_LOGIN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(50)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] ref System.Nullable<int> iD_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO", DbType="Int")] ref System.Nullable<int> eSTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(50)")] ref string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(50)")] ref string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OUT_CORREO_ELECTRONICO", DbType="NVarChar(50)")] ref string oUT_CORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OUT_PASSWORD", DbType="NVarChar(64)")] ref string oUT_PASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO, pASSWORD, iD_USUARIO, eSTADO, nOMBRE, aPELLIDOS, oUT_CORREO_ELECTRONICO, oUT_PASSWORD);
			iD_USUARIO = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eSTADO = ((System.Nullable<int>)(result.GetParameterValue(3)));
			nOMBRE = ((string)(result.GetParameterValue(4)));
			aPELLIDOS = ((string)(result.GetParameterValue(5)));
			oUT_CORREO_ELECTRONICO = ((string)(result.GetParameterValue(6)));
			oUT_PASSWORD = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_BAHEIROS")]
		public ISingleResult<SP_OBTENER_LISTA_BAHEIROSResult> SP_OBTENER_LISTA_BAHEIROS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_LISTA_BAHEIROSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_BAHEIROS_MASCOTAS")]
		public ISingleResult<SP_OBTENER_LISTA_BAHEIROS_MASCOTASResult> SP_OBTENER_LISTA_BAHEIROS_MASCOTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MASCOTA", DbType="Int")] System.Nullable<int> iD_MASCOTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MASCOTA);
			return ((ISingleResult<SP_OBTENER_LISTA_BAHEIROS_MASCOTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_CITAS_CLINICA_VETERINARIA")]
		public ISingleResult<SP_OBTENER_LISTA_CITAS_CLINICA_VETERINARIAResult> SP_OBTENER_LISTA_CITAS_CLINICA_VETERINARIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MASCOTA", DbType="Int")] System.Nullable<int> iD_MASCOTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MASCOTA);
			return ((ISingleResult<SP_OBTENER_LISTA_CITAS_CLINICA_VETERINARIAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_CLINICAS")]
		public ISingleResult<SP_OBTENER_LISTA_CLINICASResult> SP_OBTENER_LISTA_CLINICAS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_LISTA_CLINICASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_DE_DOCTORES_POR_CLINICA")]
		public ISingleResult<SP_OBTENER_LISTA_DE_DOCTORES_POR_CLINICAResult> SP_OBTENER_LISTA_DE_DOCTORES_POR_CLINICA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CLINICA_VETERINARIA", DbType="Int")] System.Nullable<int> iD_CLINICA_VETERINARIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CLINICA_VETERINARIA);
			return ((ISingleResult<SP_OBTENER_LISTA_DE_DOCTORES_POR_CLINICAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_DOCTOR")]
		public ISingleResult<SP_OBTENER_LISTA_DOCTORResult> SP_OBTENER_LISTA_DOCTOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDoctor", DbType="Int")] System.Nullable<int> idDoctor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDoctor);
			return ((ISingleResult<SP_OBTENER_LISTA_DOCTORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_FOTOS_MASCOTAS")]
		public ISingleResult<SP_OBTENER_LISTA_FOTOS_MASCOTASResult> SP_OBTENER_LISTA_FOTOS_MASCOTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Mascota", DbType="Int")] System.Nullable<int> id_Mascota)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Mascota);
			return ((ISingleResult<SP_OBTENER_LISTA_FOTOS_MASCOTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_MASCOTAS")]
		public ISingleResult<SP_OBTENER_LISTA_MASCOTASResult> SP_OBTENER_LISTA_MASCOTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USUARIO", DbType="Int")] System.Nullable<int> iD_USUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USUARIO);
			return ((ISingleResult<SP_OBTENER_LISTA_MASCOTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_MEDICAMENTOS")]
		public ISingleResult<SP_OBTENER_LISTA_MEDICAMENTOSResult> SP_OBTENER_LISTA_MEDICAMENTOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_LISTA_MEDICAMENTOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_MEDICAMENTOS_MASCOTAS")]
		public ISingleResult<SP_OBTENER_LISTA_MEDICAMENTOS_MASCOTASResult> SP_OBTENER_LISTA_MEDICAMENTOS_MASCOTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Mascota", DbType="Int")] System.Nullable<int> id_Mascota)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Mascota);
			return ((ISingleResult<SP_OBTENER_LISTA_MEDICAMENTOS_MASCOTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_VACUNAS")]
		public ISingleResult<SP_OBTENER_LISTA_VACUNASResult> SP_OBTENER_LISTA_VACUNAS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_LISTA_VACUNASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LISTA_VACUNAS_MASCOTAS")]
		public ISingleResult<SP_OBTENER_LISTA_VACUNAS_MASCOTASResult> SP_OBTENER_LISTA_VACUNAS_MASCOTAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MASCOTA", DbType="Int")] System.Nullable<int> iD_MASCOTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MASCOTA);
			return ((ISingleResult<SP_OBTENER_LISTA_VACUNAS_MASCOTASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RESTABLECER_PASSWORD")]
		public int SP_RESTABLECER_PASSWORD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="NVarChar(50)")] string cORREO_ELECTRONICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVO_PASSWORD", DbType="NVarChar(MAX)")] string nUEVO_PASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONFIRMAR_PASSWORD", DbType="NVarChar(MAX)")] string cONFIRMAR_PASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO_ELECTRONICO, nUEVO_PASSWORD, cONFIRMAR_PASSWORD);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SP_CITAS__CLINICA_VETERINARIA_MASCOTASResult
	{
		
		private System.Nullable<int> _Resultado;
		
		private System.Nullable<int> _IdError;
		
		private string _ErrorDescripcion;
		
		public SP_CITAS__CLINICA_VETERINARIA_MASCOTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Int")]
		public System.Nullable<int> Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdError", DbType="Int")]
		public System.Nullable<int> IdError
		{
			get
			{
				return this._IdError;
			}
			set
			{
				if ((this._IdError != value))
				{
					this._IdError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorDescripcion", DbType="VarChar(200)")]
		public string ErrorDescripcion
		{
			get
			{
				return this._ErrorDescripcion;
			}
			set
			{
				if ((this._ErrorDescripcion != value))
				{
					this._ErrorDescripcion = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_BAHEIROSResult
	{
		
		private int _ID_BAHEIRO;
		
		private string _TIPO_DE_BAHEIRO;
		
		private string _DESCRIPCION;
		
		public SP_OBTENER_LISTA_BAHEIROSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BAHEIRO", DbType="Int NOT NULL")]
		public int ID_BAHEIRO
		{
			get
			{
				return this._ID_BAHEIRO;
			}
			set
			{
				if ((this._ID_BAHEIRO != value))
				{
					this._ID_BAHEIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_DE_BAHEIRO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string TIPO_DE_BAHEIRO
		{
			get
			{
				return this._TIPO_DE_BAHEIRO;
			}
			set
			{
				if ((this._TIPO_DE_BAHEIRO != value))
				{
					this._TIPO_DE_BAHEIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(255)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_BAHEIROS_MASCOTASResult
	{
		
		private int _ID_BAHEIROS_MASCOTA;
		
		private System.Nullable<int> _ID_MASCOTA;
		
		private string _NOMBRE_MASCOTA;
		
		private System.Nullable<int> _ID_BAHEIRO;
		
		private string _NOMBRE_BAHEIRO;
		
		private string _DESCRIPCION_BAHEIRO;
		
		private System.Nullable<System.DateTime> _FECHA_Y_HORA_BAHEIRO;
		
		private System.Nullable<System.DateTime> _FECHA_Y_HORA_PROXIMO_BAHEIRO;
		
		private string _NOTAS;
		
		public SP_OBTENER_LISTA_BAHEIROS_MASCOTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BAHEIROS_MASCOTA", DbType="Int NOT NULL")]
		public int ID_BAHEIROS_MASCOTA
		{
			get
			{
				return this._ID_BAHEIROS_MASCOTA;
			}
			set
			{
				if ((this._ID_BAHEIROS_MASCOTA != value))
				{
					this._ID_BAHEIROS_MASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MASCOTA", DbType="Int")]
		public System.Nullable<int> ID_MASCOTA
		{
			get
			{
				return this._ID_MASCOTA;
			}
			set
			{
				if ((this._ID_MASCOTA != value))
				{
					this._ID_MASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MASCOTA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_MASCOTA
		{
			get
			{
				return this._NOMBRE_MASCOTA;
			}
			set
			{
				if ((this._NOMBRE_MASCOTA != value))
				{
					this._NOMBRE_MASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BAHEIRO", DbType="Int")]
		public System.Nullable<int> ID_BAHEIRO
		{
			get
			{
				return this._ID_BAHEIRO;
			}
			set
			{
				if ((this._ID_BAHEIRO != value))
				{
					this._ID_BAHEIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_BAHEIRO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE_BAHEIRO
		{
			get
			{
				return this._NOMBRE_BAHEIRO;
			}
			set
			{
				if ((this._NOMBRE_BAHEIRO != value))
				{
					this._NOMBRE_BAHEIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION_BAHEIRO", DbType="NVarChar(255)")]
		public string DESCRIPCION_BAHEIRO
		{
			get
			{
				return this._DESCRIPCION_BAHEIRO;
			}
			set
			{
				if ((this._DESCRIPCION_BAHEIRO != value))
				{
					this._DESCRIPCION_BAHEIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_Y_HORA_BAHEIRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_Y_HORA_BAHEIRO
		{
			get
			{
				return this._FECHA_Y_HORA_BAHEIRO;
			}
			set
			{
				if ((this._FECHA_Y_HORA_BAHEIRO != value))
				{
					this._FECHA_Y_HORA_BAHEIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_Y_HORA_PROXIMO_BAHEIRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_Y_HORA_PROXIMO_BAHEIRO
		{
			get
			{
				return this._FECHA_Y_HORA_PROXIMO_BAHEIRO;
			}
			set
			{
				if ((this._FECHA_Y_HORA_PROXIMO_BAHEIRO != value))
				{
					this._FECHA_Y_HORA_PROXIMO_BAHEIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTAS", DbType="NVarChar(255)")]
		public string NOTAS
		{
			get
			{
				return this._NOTAS;
			}
			set
			{
				if ((this._NOTAS != value))
				{
					this._NOTAS = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_CITAS_CLINICA_VETERINARIAResult
	{
		
		private int _ID_CITA;
		
		private System.Nullable<int> _ID_MASCOTA;
		
		private string _NOMBRE_MASCOTA;
		
		private System.Nullable<int> _ID_CLINICA_VETERINARIA;
		
		private string _NOMBRE_DE_LA_CLINICA;
		
		private System.Nullable<int> _ID_DOCTOR;
		
		private string _NOMBRE_DEL_DOCTOR;
		
		private string _DIRECCION_DE_LA_CLINICA;
		
		private string _TELEFONO;
		
		private System.Nullable<System.DateTime> _FECHA_Y_HORA;
		
		private string _DESCRIPCION;
		
		private string _NOTAS;
		
		public SP_OBTENER_LISTA_CITAS_CLINICA_VETERINARIAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CITA", DbType="Int NOT NULL")]
		public int ID_CITA
		{
			get
			{
				return this._ID_CITA;
			}
			set
			{
				if ((this._ID_CITA != value))
				{
					this._ID_CITA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MASCOTA", DbType="Int")]
		public System.Nullable<int> ID_MASCOTA
		{
			get
			{
				return this._ID_MASCOTA;
			}
			set
			{
				if ((this._ID_MASCOTA != value))
				{
					this._ID_MASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MASCOTA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_MASCOTA
		{
			get
			{
				return this._NOMBRE_MASCOTA;
			}
			set
			{
				if ((this._NOMBRE_MASCOTA != value))
				{
					this._NOMBRE_MASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLINICA_VETERINARIA", DbType="Int")]
		public System.Nullable<int> ID_CLINICA_VETERINARIA
		{
			get
			{
				return this._ID_CLINICA_VETERINARIA;
			}
			set
			{
				if ((this._ID_CLINICA_VETERINARIA != value))
				{
					this._ID_CLINICA_VETERINARIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_DE_LA_CLINICA", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE_DE_LA_CLINICA
		{
			get
			{
				return this._NOMBRE_DE_LA_CLINICA;
			}
			set
			{
				if ((this._NOMBRE_DE_LA_CLINICA != value))
				{
					this._NOMBRE_DE_LA_CLINICA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOCTOR", DbType="Int")]
		public System.Nullable<int> ID_DOCTOR
		{
			get
			{
				return this._ID_DOCTOR;
			}
			set
			{
				if ((this._ID_DOCTOR != value))
				{
					this._ID_DOCTOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_DEL_DOCTOR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_DEL_DOCTOR
		{
			get
			{
				return this._NOMBRE_DEL_DOCTOR;
			}
			set
			{
				if ((this._NOMBRE_DEL_DOCTOR != value))
				{
					this._NOMBRE_DEL_DOCTOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION_DE_LA_CLINICA", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DIRECCION_DE_LA_CLINICA
		{
			get
			{
				return this._DIRECCION_DE_LA_CLINICA;
			}
			set
			{
				if ((this._DIRECCION_DE_LA_CLINICA != value))
				{
					this._DIRECCION_DE_LA_CLINICA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_Y_HORA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_Y_HORA
		{
			get
			{
				return this._FECHA_Y_HORA;
			}
			set
			{
				if ((this._FECHA_Y_HORA != value))
				{
					this._FECHA_Y_HORA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(255)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTAS", DbType="NVarChar(255)")]
		public string NOTAS
		{
			get
			{
				return this._NOTAS;
			}
			set
			{
				if ((this._NOTAS != value))
				{
					this._NOTAS = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_CLINICASResult
	{
		
		private int _ID_CLINICA_VETERINARIA;
		
		private string _NOMBRE_CLINICA_VETERINARIA;
		
		private string _DIRECCION;
		
		private string _TELEFONO;
		
		public SP_OBTENER_LISTA_CLINICASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLINICA_VETERINARIA", DbType="Int NOT NULL")]
		public int ID_CLINICA_VETERINARIA
		{
			get
			{
				return this._ID_CLINICA_VETERINARIA;
			}
			set
			{
				if ((this._ID_CLINICA_VETERINARIA != value))
				{
					this._ID_CLINICA_VETERINARIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CLINICA_VETERINARIA", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE_CLINICA_VETERINARIA
		{
			get
			{
				return this._NOMBRE_CLINICA_VETERINARIA;
			}
			set
			{
				if ((this._NOMBRE_CLINICA_VETERINARIA != value))
				{
					this._NOMBRE_CLINICA_VETERINARIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_DE_DOCTORES_POR_CLINICAResult
	{
		
		private int _ID_CLINICA_VETERINARIA;
		
		private int _ID_DOCTOR;
		
		private string _NOMBRE_DOCTOR;
		
		private string _TELEFONO;
		
		private string _CORREO_ELECTRONICO;
		
		public SP_OBTENER_LISTA_DE_DOCTORES_POR_CLINICAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLINICA_VETERINARIA", DbType="Int NOT NULL")]
		public int ID_CLINICA_VETERINARIA
		{
			get
			{
				return this._ID_CLINICA_VETERINARIA;
			}
			set
			{
				if ((this._ID_CLINICA_VETERINARIA != value))
				{
					this._ID_CLINICA_VETERINARIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOCTOR", DbType="Int NOT NULL")]
		public int ID_DOCTOR
		{
			get
			{
				return this._ID_DOCTOR;
			}
			set
			{
				if ((this._ID_DOCTOR != value))
				{
					this._ID_DOCTOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_DOCTOR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_DOCTOR
		{
			get
			{
				return this._NOMBRE_DOCTOR;
			}
			set
			{
				if ((this._NOMBRE_DOCTOR != value))
				{
					this._NOMBRE_DOCTOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_DOCTORResult
	{
		
		private int _ID_DOCTOR;
		
		private string _NOMBRE;
		
		private string _CORREO_ELECTRONICO;
		
		private string _TELEFONO;
		
		public SP_OBTENER_LISTA_DOCTORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOCTOR", DbType="Int NOT NULL")]
		public int ID_DOCTOR
		{
			get
			{
				return this._ID_DOCTOR;
			}
			set
			{
				if ((this._ID_DOCTOR != value))
				{
					this._ID_DOCTOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_FOTOS_MASCOTASResult
	{
		
		private int _ID_FOTO;
		
		private System.Data.Linq.Binary _FOTO;
		
		private string _DESCRIPCION;
		
		public SP_OBTENER_LISTA_FOTOS_MASCOTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FOTO", DbType="Int NOT NULL")]
		public int ID_FOTO
		{
			get
			{
				return this._ID_FOTO;
			}
			set
			{
				if ((this._ID_FOTO != value))
				{
					this._ID_FOTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary FOTO
		{
			get
			{
				return this._FOTO;
			}
			set
			{
				if ((this._FOTO != value))
				{
					this._FOTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(255)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_MASCOTASResult
	{
		
		private int _ID_MASCOTA;
		
		private int _ID_USUARIO;
		
		private string _NOMBRE;
		
		private string _ESPECIE;
		
		private string _RAZA;
		
		private System.DateTime _FECHA_NACIMIENTO;
		
		private System.DateTime _FECHA_Y_HORA_DE_REGISTRO;
		
		private System.Nullable<System.DateTime> _FECHA_Y_HORA_PROXIMO_BAHEIRO;
		
		public SP_OBTENER_LISTA_MASCOTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MASCOTA", DbType="Int NOT NULL")]
		public int ID_MASCOTA
		{
			get
			{
				return this._ID_MASCOTA;
			}
			set
			{
				if ((this._ID_MASCOTA != value))
				{
					this._ID_MASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPECIE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ESPECIE
		{
			get
			{
				return this._ESPECIE;
			}
			set
			{
				if ((this._ESPECIE != value))
				{
					this._ESPECIE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAZA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RAZA
		{
			get
			{
				return this._RAZA;
			}
			set
			{
				if ((this._RAZA != value))
				{
					this._RAZA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this._FECHA_NACIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_Y_HORA_DE_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_Y_HORA_DE_REGISTRO
		{
			get
			{
				return this._FECHA_Y_HORA_DE_REGISTRO;
			}
			set
			{
				if ((this._FECHA_Y_HORA_DE_REGISTRO != value))
				{
					this._FECHA_Y_HORA_DE_REGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_Y_HORA_PROXIMO_BAHEIRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_Y_HORA_PROXIMO_BAHEIRO
		{
			get
			{
				return this._FECHA_Y_HORA_PROXIMO_BAHEIRO;
			}
			set
			{
				if ((this._FECHA_Y_HORA_PROXIMO_BAHEIRO != value))
				{
					this._FECHA_Y_HORA_PROXIMO_BAHEIRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_MEDICAMENTOSResult
	{
		
		private int _ID_MEDICAMENTO;
		
		private string _NOMBRE;
		
		private string _CATEGORIA;
		
		private string _DESCRIPCION;
		
		private System.Nullable<System.DateTime> _FECHA_VENCIMIENTO;
		
		public SP_OBTENER_LISTA_MEDICAMENTOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MEDICAMENTO", DbType="Int NOT NULL")]
		public int ID_MEDICAMENTO
		{
			get
			{
				return this._ID_MEDICAMENTO;
			}
			set
			{
				if ((this._ID_MEDICAMENTO != value))
				{
					this._ID_MEDICAMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="VarChar(20)")]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(255)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_VENCIMIENTO", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_VENCIMIENTO
		{
			get
			{
				return this._FECHA_VENCIMIENTO;
			}
			set
			{
				if ((this._FECHA_VENCIMIENTO != value))
				{
					this._FECHA_VENCIMIENTO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_MEDICAMENTOS_MASCOTASResult
	{
		
		private System.Nullable<int> _ID_MASCOTA;
		
		private string _NOMBRE_MASCOTA;
		
		private System.Nullable<int> _ID_MEDICAMENTO;
		
		private string _NOMBRE_MEDICAMENTO;
		
		private string _CATEGORIA;
		
		private string _MODO_DE_ADMINISTRACION;
		
		private System.Nullable<System.TimeSpan> _HORA_DE_INGESTA;
		
		private System.Nullable<System.DateTime> _FECHA_INICIO;
		
		private System.Nullable<System.DateTime> _FECHA_FIN;
		
		private string _NOTAS;
		
		public SP_OBTENER_LISTA_MEDICAMENTOS_MASCOTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MASCOTA", DbType="Int")]
		public System.Nullable<int> ID_MASCOTA
		{
			get
			{
				return this._ID_MASCOTA;
			}
			set
			{
				if ((this._ID_MASCOTA != value))
				{
					this._ID_MASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MASCOTA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_MASCOTA
		{
			get
			{
				return this._NOMBRE_MASCOTA;
			}
			set
			{
				if ((this._NOMBRE_MASCOTA != value))
				{
					this._NOMBRE_MASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MEDICAMENTO", DbType="Int")]
		public System.Nullable<int> ID_MEDICAMENTO
		{
			get
			{
				return this._ID_MEDICAMENTO;
			}
			set
			{
				if ((this._ID_MEDICAMENTO != value))
				{
					this._ID_MEDICAMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MEDICAMENTO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_MEDICAMENTO
		{
			get
			{
				return this._NOMBRE_MEDICAMENTO;
			}
			set
			{
				if ((this._NOMBRE_MEDICAMENTO != value))
				{
					this._NOMBRE_MEDICAMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="VarChar(20)")]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODO_DE_ADMINISTRACION", DbType="VarChar(20)")]
		public string MODO_DE_ADMINISTRACION
		{
			get
			{
				return this._MODO_DE_ADMINISTRACION;
			}
			set
			{
				if ((this._MODO_DE_ADMINISTRACION != value))
				{
					this._MODO_DE_ADMINISTRACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_DE_INGESTA", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA_DE_INGESTA
		{
			get
			{
				return this._HORA_DE_INGESTA;
			}
			set
			{
				if ((this._HORA_DE_INGESTA != value))
				{
					this._HORA_DE_INGESTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INICIO", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_INICIO
		{
			get
			{
				return this._FECHA_INICIO;
			}
			set
			{
				if ((this._FECHA_INICIO != value))
				{
					this._FECHA_INICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_FIN", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_FIN
		{
			get
			{
				return this._FECHA_FIN;
			}
			set
			{
				if ((this._FECHA_FIN != value))
				{
					this._FECHA_FIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTAS", DbType="NVarChar(255)")]
		public string NOTAS
		{
			get
			{
				return this._NOTAS;
			}
			set
			{
				if ((this._NOTAS != value))
				{
					this._NOTAS = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_VACUNASResult
	{
		
		private int _ID_VACUNA;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private System.Nullable<System.DateTime> _FECHA_VENCIMIENTO;
		
		public SP_OBTENER_LISTA_VACUNASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VACUNA", DbType="Int NOT NULL")]
		public int ID_VACUNA
		{
			get
			{
				return this._ID_VACUNA;
			}
			set
			{
				if ((this._ID_VACUNA != value))
				{
					this._ID_VACUNA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(255)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_VENCIMIENTO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_VENCIMIENTO
		{
			get
			{
				return this._FECHA_VENCIMIENTO;
			}
			set
			{
				if ((this._FECHA_VENCIMIENTO != value))
				{
					this._FECHA_VENCIMIENTO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LISTA_VACUNAS_MASCOTASResult
	{
		
		private int _IDMASCOTAVACUNA;
		
		private int _IDMASCOTA;
		
		private string _NOMBRE_MASCOTA;
		
		private int _IDVACUNA;
		
		private int _DOSIS;
		
		private string _NOMBRE_VACUNA;
		
		private string _DESCRIPCION_VACUNA;
		
		private System.Nullable<System.DateTime> _VACUNA;
		
		private System.Nullable<System.DateTime> _FECHA_Y_HORA_PROXIMAAPLICACION;
		
		private string _COMENTARIOS;
		
		public SP_OBTENER_LISTA_VACUNAS_MASCOTASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMASCOTAVACUNA", DbType="Int NOT NULL")]
		public int IDMASCOTAVACUNA
		{
			get
			{
				return this._IDMASCOTAVACUNA;
			}
			set
			{
				if ((this._IDMASCOTAVACUNA != value))
				{
					this._IDMASCOTAVACUNA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMASCOTA", DbType="Int NOT NULL")]
		public int IDMASCOTA
		{
			get
			{
				return this._IDMASCOTA;
			}
			set
			{
				if ((this._IDMASCOTA != value))
				{
					this._IDMASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MASCOTA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_MASCOTA
		{
			get
			{
				return this._NOMBRE_MASCOTA;
			}
			set
			{
				if ((this._NOMBRE_MASCOTA != value))
				{
					this._NOMBRE_MASCOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDVACUNA", DbType="Int NOT NULL")]
		public int IDVACUNA
		{
			get
			{
				return this._IDVACUNA;
			}
			set
			{
				if ((this._IDVACUNA != value))
				{
					this._IDVACUNA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSIS", DbType="Int NOT NULL")]
		public int DOSIS
		{
			get
			{
				return this._DOSIS;
			}
			set
			{
				if ((this._DOSIS != value))
				{
					this._DOSIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_VACUNA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_VACUNA
		{
			get
			{
				return this._NOMBRE_VACUNA;
			}
			set
			{
				if ((this._NOMBRE_VACUNA != value))
				{
					this._NOMBRE_VACUNA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION_VACUNA", DbType="NVarChar(255)")]
		public string DESCRIPCION_VACUNA
		{
			get
			{
				return this._DESCRIPCION_VACUNA;
			}
			set
			{
				if ((this._DESCRIPCION_VACUNA != value))
				{
					this._DESCRIPCION_VACUNA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VACUNA", DbType="DateTime")]
		public System.Nullable<System.DateTime> VACUNA
		{
			get
			{
				return this._VACUNA;
			}
			set
			{
				if ((this._VACUNA != value))
				{
					this._VACUNA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_Y_HORA_PROXIMAAPLICACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_Y_HORA_PROXIMAAPLICACION
		{
			get
			{
				return this._FECHA_Y_HORA_PROXIMAAPLICACION;
			}
			set
			{
				if ((this._FECHA_Y_HORA_PROXIMAAPLICACION != value))
				{
					this._FECHA_Y_HORA_PROXIMAAPLICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMENTARIOS", DbType="VarChar(255)")]
		public string COMENTARIOS
		{
			get
			{
				return this._COMENTARIOS;
			}
			set
			{
				if ((this._COMENTARIOS != value))
				{
					this._COMENTARIOS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
